### ISSUE TITLE
Subdomain

### ISSUE THREAD

**Issue by jbelien** [EqualStreetNames/equalstreetnames-leipzig#1]
@gislars or @RobinLinde Could one of you create a sub-domain (`equalstreetnames-leipzig.openstreetmap.de` or `leipzig.openstreetmap.eu`) with a `CNAME` record pointing to `equalstreetnames.github.io` for the city of Leipzig, Germany.

A group of students from the University of Leipzig that contacted me to replicate the project in Leipzig ; they are working on the data (OpenStreetMap + WikiData) but don't have technical background.

Thanks a lot !

**Comment by RobinLinde** [comment]
@jbelien CNAME record for `leipzig.equalstreetnames.eu` should now be in place

**Comment by jbelien** [comment]
@RobinLinde You're ... AWESOME ! 🎉
